credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: abc # This should be hashed using stauth.Hasher(['abc']).generate()[0]
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
