credentials:
  usernames:
    admin:
      email: admin@domain.com
      name: Admin User
      password: your_hashed_password # Use stauth.Hasher(['your_password']).generate()
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - admin@domain.com
